# Generated by Django 5.1 on 2024-10-19 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='police.policemodel'),
        ),
        migrations.AlterField(
            model_name='crime',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Investigating', 'Investigating'), ('Request Pending', 'Request Pending'), ('Similiar Repoted', 'Similar Reported')], max_length=50),
        ),
    ]
