# Generated by Django 5.1 on 2024-10-19 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0002_evidence_added_by_alter_crime_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='witness',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='police.policemodel'),
        ),
    ]
