# Generated by Django 5.1.2 on 2024-10-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0003_witness_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policemodel',
            name='status',
        ),
        migrations.AlterField(
            model_name='crime',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Investigating', 'Investigating'), ('Request Pending', 'Request Pending')], max_length=50),
        ),
    ]
