# Generated by Django 5.1 on 2024-10-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0004_remove_policemodel_status_alter_crime_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('In Jail', 'In Jail'), ('Free', 'Free')], max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Females')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('crime', models.ManyToManyField(to='police.crime')),
            ],
        ),
    ]
