# Generated by Django 5.1 on 2024-10-31 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0005_criminal'),
        ('police', '0006_suspect_added_by_victim_added_by'),
    ]

    operations = [
    ]
