# Generated by Django 5.1.2 on 2024-10-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Civilian', 'Civilian'), ('Admin', 'Admin'), ('Police', 'Police')], max_length=15),
        ),
    ]
